import Head from 'next/head'
import { useTranslation } from 'next-i18next'
import { serverSideTranslations } from 'next-i18next/serverSideTranslations'

import Footer from '@/components/footer/Footer'

import Collection from './landing/Collection'
import Exhibition from './landing/Exhibition'
import Hero from './landing/Hero'
import News from './landing/News'

export const getServerSideProps = async ({ locale }) => ({
  props: {
    ...(await serverSideTranslations(locale, ['common'])),
  },
})

const LandingPage = () => {
  const { t } = useTranslation('common')

  return (
    <>
      <Head>
        <title>{t('landing_collection_title')}</title>
        <meta name='description' content='Generated by create next app' />
      </Head>
      <main className='bg-platinum text-brown'>
        <Hero />
        <Collection />
        <News />
        <Exhibition />
        <Footer />
      </main>
    </>
  )
}

export default LandingPage
